pyprland.plugins = [ "scratchpads" ]

#[scratchpads.term]
#animation = "fromTop"
#command = "[term_classed] main-dropterm"
#class = "main-dropterm"
#size = "75% 60%"
#max_size = "1920px 100%"
#margin = 20

#[scratchpads.alacritty]
#animation = "fromTop"
#command = "[alacritty_classed] alacritty-quake"
#class = "alacritty-quake"
#size = "75% 67%"
#max_size = "1920px 100%"
#margin = 32

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "74% 60%"
max_size = "2220px 100%"
margin = 30
hysteresis=0.8
preserve_aspect = true
lazy = true


[scratchpads.obsidian]
animation = "fromRight"
command = "obsidian"
class = "obsidian"
size = "34% 97%"
position = "66% 30px"
hysteresis=0.8
preserve_aspect = true
excludes = ["chat-gpt","dolphin","typora"]
lazy = true

[scratchpads.chat-gpt]
animation = "fromRight"
command = "qutebrowser"
class = "org.qutebrowser.qutebrowser"
size = "34% 97%"
position = "66% 30px"
hysteresis=0.8
preserve_aspect = true
excludes = ["obsidian","dolphin","typora"]
lazy = true

[scratchpads.dolphin]
animation = "fromRight"
command = "dolphin"
class = "org.kde.dolphin"
size = "22% 96%"
position = "78% 34px"
hysteresis=0.8
preserve_aspect = true
excludes = ["obsidian","chat-gpt","typora"]
lazy = true


[scratchpads.typora]
animation = "fromBottom"
command = "typora"
class = "Typora"
size = "25% 80%"
unfocus="hide"
hysteresis=0.8
preserve_aspect = true
excludes = ["obsidian","chat-gpt","dolphin"]
lazy = true


#[scratchpads.wezterm]
#animation = "fromTop"
#command = "__NV_DISABLE_EXPLICIT_SYNC=1 wezterm"
#class = "org.wezfurlong.wezterm"
#size = "90% 67%"
#max_size = "2240px 100%"
#margin = 32

