pyprland.plugins = [ "shortcuts_menu" ]

[shortcuts_menu]
engine = "rofi"
parameters = "-p ⚡ -dmenu -matching fuzzy -i -theme ~/.config/rofi/themes/themes/nord.rasi"

[shortcuts_menu.entries]

"Bookmarks" = [
    {name="path", options=["/home/ichelema/", 
                        "/home/ichelema/.config",
                        "/home/ichelema/.config/hypr/"]},
    {name="explorer", options=["dolphin", "krusader"]},
    "[explorer] [path]"
]

[shortcuts_menu.entries.Utility]
"Color picker" = [
    {name="format", options=["hex", "rgb", "hsv", "hsl", "cmyk"]},
    "sleep 0.5; hyprpicker --format [format] | wl-copy"
]


[shortcuts_menu.entries.Utility.Screnshot]
partial = "/home/ichelema/.local/share/bin/screenshot.sh s"
partial_frozen = "/home/ichelema/.local/share/bin/screenshot.sh sf"
monitor = "/home/ichelema/.local/share/bin/screenshot.sh m"
